name: 'Mirror Folder Content'

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
        
    steps:
      - name: mirror
        id: mirror
        uses: bridgelightcloud/github-mirror-action@v2
        with:
          origin: wterkaj/vebjs
