name: Mirror Folder Content

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v4
        with:
          repository: wterkaj/vebjs
          path: img

      - name: Mirror Folder Content
        run: |
          cp -r img/* .
          git add .
          git commit -m "Mirror folder content from source repository"
          git push
