name: Mirror Folder Content

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
      - name: Checkout Source Repository
        uses: actions/checkout@v2
        with:
          repository: difactory/repository
          path: ontoeng

      - name: Mirror Folder Content
        run: |
          cp -r ontoeng/* .
          git add .
          git commit -m "Mirror folder content from source repository"
          git push
